/*
API

API for traces

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StartTraceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartTraceRequest{}

// StartTraceRequest struct for StartTraceRequest
type StartTraceRequest struct {
	GroupUuid  *string `json:"group_uuid,omitempty"`
	ParentUuid *string `json:"parent_uuid,omitempty"`
	Title      string  `json:"title"`
	Component  string  `json:"component"`
}

// NewStartTraceRequest instantiates a new StartTraceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartTraceRequest(title string, component string) *StartTraceRequest {
	this := StartTraceRequest{}
	this.Title = title
	this.Component = component
	return &this
}

// NewStartTraceRequestWithDefaults instantiates a new StartTraceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartTraceRequestWithDefaults() *StartTraceRequest {
	this := StartTraceRequest{}
	return &this
}

// GetGroupUuid returns the GroupUuid field value if set, zero value otherwise.
func (o *StartTraceRequest) GetGroupUuid() string {
	if o == nil || IsNil(o.GroupUuid) {
		var ret string
		return ret
	}
	return *o.GroupUuid
}

// GetGroupUuidOk returns a tuple with the GroupUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartTraceRequest) GetGroupUuidOk() (*string, bool) {
	if o == nil || IsNil(o.GroupUuid) {
		return nil, false
	}
	return o.GroupUuid, true
}

// HasGroupUuid returns a boolean if a field has been set.
func (o *StartTraceRequest) HasGroupUuid() bool {
	if o != nil && !IsNil(o.GroupUuid) {
		return true
	}

	return false
}

// SetGroupUuid gets a reference to the given string and assigns it to the GroupUuid field.
func (o *StartTraceRequest) SetGroupUuid(v string) {
	o.GroupUuid = &v
}

// GetParentUuid returns the ParentUuid field value if set, zero value otherwise.
func (o *StartTraceRequest) GetParentUuid() string {
	if o == nil || IsNil(o.ParentUuid) {
		var ret string
		return ret
	}
	return *o.ParentUuid
}

// GetParentUuidOk returns a tuple with the ParentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartTraceRequest) GetParentUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ParentUuid) {
		return nil, false
	}
	return o.ParentUuid, true
}

// HasParentUuid returns a boolean if a field has been set.
func (o *StartTraceRequest) HasParentUuid() bool {
	if o != nil && !IsNil(o.ParentUuid) {
		return true
	}

	return false
}

// SetParentUuid gets a reference to the given string and assigns it to the ParentUuid field.
func (o *StartTraceRequest) SetParentUuid(v string) {
	o.ParentUuid = &v
}

// GetTitle returns the Title field value
func (o *StartTraceRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *StartTraceRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *StartTraceRequest) SetTitle(v string) {
	o.Title = v
}

// GetComponent returns the Component field value
func (o *StartTraceRequest) GetComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Component
}

// GetComponentOk returns a tuple with the Component field value
// and a boolean to check if the value has been set.
func (o *StartTraceRequest) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Component, true
}

// SetComponent sets field value
func (o *StartTraceRequest) SetComponent(v string) {
	o.Component = v
}

func (o StartTraceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartTraceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupUuid) {
		toSerialize["group_uuid"] = o.GroupUuid
	}
	if !IsNil(o.ParentUuid) {
		toSerialize["parent_uuid"] = o.ParentUuid
	}
	toSerialize["title"] = o.Title
	toSerialize["component"] = o.Component
	return toSerialize, nil
}

type NullableStartTraceRequest struct {
	value *StartTraceRequest
	isSet bool
}

func (v NullableStartTraceRequest) Get() *StartTraceRequest {
	return v.value
}

func (v *NullableStartTraceRequest) Set(val *StartTraceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartTraceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartTraceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartTraceRequest(val *StartTraceRequest) *NullableStartTraceRequest {
	return &NullableStartTraceRequest{value: val, isSet: true}
}

func (v NullableStartTraceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartTraceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
