/*
API

API for traces

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateGroupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGroupResponse{}

// CreateGroupResponse struct for CreateGroupResponse
type CreateGroupResponse struct {
	Uuid string `json:"uuid"`
}

// NewCreateGroupResponse instantiates a new CreateGroupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGroupResponse(uuid string) *CreateGroupResponse {
	this := CreateGroupResponse{}
	this.Uuid = uuid
	return &this
}

// NewCreateGroupResponseWithDefaults instantiates a new CreateGroupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGroupResponseWithDefaults() *CreateGroupResponse {
	this := CreateGroupResponse{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *CreateGroupResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *CreateGroupResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *CreateGroupResponse) SetUuid(v string) {
	o.Uuid = v
}

func (o CreateGroupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGroupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	return toSerialize, nil
}

type NullableCreateGroupResponse struct {
	value *CreateGroupResponse
	isSet bool
}

func (v NullableCreateGroupResponse) Get() *CreateGroupResponse {
	return v.value
}

func (v *NullableCreateGroupResponse) Set(val *CreateGroupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGroupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGroupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGroupResponse(val *CreateGroupResponse) *NullableCreateGroupResponse {
	return &NullableCreateGroupResponse{value: val, isSet: true}
}

func (v NullableCreateGroupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGroupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
