/*
API

API for traces

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StartTraceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartTraceResponse{}

// StartTraceResponse struct for StartTraceResponse
type StartTraceResponse struct {
	Uuid       string  `json:"uuid"`
	GroupUuid  *string `json:"group_uuid,omitempty"`
	ParentUuid *string `json:"parent_uuid,omitempty"`
	Start      string  `json:"start"`
	End        string  `json:"end"`
	Title      string  `json:"title"`
	Component  string  `json:"component"`
	Finished   bool    `json:"finished"`
}

// NewStartTraceResponse instantiates a new StartTraceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartTraceResponse(uuid string, start string, end string, title string, component string, finished bool) *StartTraceResponse {
	this := StartTraceResponse{}
	this.Uuid = uuid
	this.Start = start
	this.End = end
	this.Title = title
	this.Component = component
	this.Finished = finished
	return &this
}

// NewStartTraceResponseWithDefaults instantiates a new StartTraceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartTraceResponseWithDefaults() *StartTraceResponse {
	this := StartTraceResponse{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *StartTraceResponse) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *StartTraceResponse) SetUuid(v string) {
	o.Uuid = v
}

// GetGroupUuid returns the GroupUuid field value if set, zero value otherwise.
func (o *StartTraceResponse) GetGroupUuid() string {
	if o == nil || IsNil(o.GroupUuid) {
		var ret string
		return ret
	}
	return *o.GroupUuid
}

// GetGroupUuidOk returns a tuple with the GroupUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetGroupUuidOk() (*string, bool) {
	if o == nil || IsNil(o.GroupUuid) {
		return nil, false
	}
	return o.GroupUuid, true
}

// HasGroupUuid returns a boolean if a field has been set.
func (o *StartTraceResponse) HasGroupUuid() bool {
	if o != nil && !IsNil(o.GroupUuid) {
		return true
	}

	return false
}

// SetGroupUuid gets a reference to the given string and assigns it to the GroupUuid field.
func (o *StartTraceResponse) SetGroupUuid(v string) {
	o.GroupUuid = &v
}

// GetParentUuid returns the ParentUuid field value if set, zero value otherwise.
func (o *StartTraceResponse) GetParentUuid() string {
	if o == nil || IsNil(o.ParentUuid) {
		var ret string
		return ret
	}
	return *o.ParentUuid
}

// GetParentUuidOk returns a tuple with the ParentUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetParentUuidOk() (*string, bool) {
	if o == nil || IsNil(o.ParentUuid) {
		return nil, false
	}
	return o.ParentUuid, true
}

// HasParentUuid returns a boolean if a field has been set.
func (o *StartTraceResponse) HasParentUuid() bool {
	if o != nil && !IsNil(o.ParentUuid) {
		return true
	}

	return false
}

// SetParentUuid gets a reference to the given string and assigns it to the ParentUuid field.
func (o *StartTraceResponse) SetParentUuid(v string) {
	o.ParentUuid = &v
}

// GetStart returns the Start field value
func (o *StartTraceResponse) GetStart() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetStartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *StartTraceResponse) SetStart(v string) {
	o.Start = v
}

// GetEnd returns the End field value
func (o *StartTraceResponse) GetEnd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.End
}

// GetEndOk returns a tuple with the End field value
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.End, true
}

// SetEnd sets field value
func (o *StartTraceResponse) SetEnd(v string) {
	o.End = v
}

// GetTitle returns the Title field value
func (o *StartTraceResponse) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *StartTraceResponse) SetTitle(v string) {
	o.Title = v
}

// GetComponent returns the Component field value
func (o *StartTraceResponse) GetComponent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Component
}

// GetComponentOk returns a tuple with the Component field value
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetComponentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Component, true
}

// SetComponent sets field value
func (o *StartTraceResponse) SetComponent(v string) {
	o.Component = v
}

// GetFinished returns the Finished field value
func (o *StartTraceResponse) GetFinished() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Finished
}

// GetFinishedOk returns a tuple with the Finished field value
// and a boolean to check if the value has been set.
func (o *StartTraceResponse) GetFinishedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Finished, true
}

// SetFinished sets field value
func (o *StartTraceResponse) SetFinished(v bool) {
	o.Finished = v
}

func (o StartTraceResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartTraceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	if !IsNil(o.GroupUuid) {
		toSerialize["group_uuid"] = o.GroupUuid
	}
	if !IsNil(o.ParentUuid) {
		toSerialize["parent_uuid"] = o.ParentUuid
	}
	toSerialize["start"] = o.Start
	toSerialize["end"] = o.End
	toSerialize["title"] = o.Title
	toSerialize["component"] = o.Component
	toSerialize["finished"] = o.Finished
	return toSerialize, nil
}

type NullableStartTraceResponse struct {
	value *StartTraceResponse
	isSet bool
}

func (v NullableStartTraceResponse) Get() *StartTraceResponse {
	return v.value
}

func (v *NullableStartTraceResponse) Set(val *StartTraceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStartTraceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStartTraceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartTraceResponse(val *StartTraceResponse) *NullableStartTraceResponse {
	return &NullableStartTraceResponse{value: val, isSet: true}
}

func (v NullableStartTraceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartTraceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
