/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)

// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface {
	CreateAlertConfig(http.ResponseWriter, *http.Request)
	CreateGroup(http.ResponseWriter, *http.Request)
	DeleteAlertConfig(http.ResponseWriter, *http.Request)
	EndTrace(http.ResponseWriter, *http.Request)
	FixAlert(http.ResponseWriter, *http.Request)
	FixEvent(http.ResponseWriter, *http.Request)
	GetAlertConfigList(http.ResponseWriter, *http.Request)
	GetAlertList(http.ResponseWriter, *http.Request)
	GetEvent(http.ResponseWriter, *http.Request)
	GetEventList(http.ResponseWriter, *http.Request)
	GetGroup(http.ResponseWriter, *http.Request)
	GetGroupList(http.ResponseWriter, *http.Request)
	SendEvent(http.ResponseWriter, *http.Request)
	StartTrace(http.ResponseWriter, *http.Request)
}

// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface {
	CreateAlertConfig(context.Context, AlertConfig) (ImplResponse, error)
	CreateGroup(context.Context) (ImplResponse, error)
	DeleteAlertConfig(context.Context, string) (ImplResponse, error)
	EndTrace(context.Context, string) (ImplResponse, error)
	FixAlert(context.Context, string) (ImplResponse, error)
	FixEvent(context.Context, string) (ImplResponse, error)
	GetAlertConfigList(context.Context) (ImplResponse, error)
	GetAlertList(context.Context) (ImplResponse, error)
	GetEvent(context.Context, string) (ImplResponse, error)
	GetEventList(context.Context) (ImplResponse, error)
	GetGroup(context.Context, string) (ImplResponse, error)
	GetGroupList(context.Context, Filters) (ImplResponse, error)
	SendEvent(context.Context, SendEventRequest) (ImplResponse, error)
	StartTrace(context.Context, StartTraceRequest) (ImplResponse, error)
}
