/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ImplResponse response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
