/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetAlertListResponseItemsInner struct {
	Uuid string `json:"uuid,omitempty"`

	Message string `json:"message,omitempty"`

	Time string `json:"time,omitempty"`

	Event Event `json:"event,omitempty"`
}

// AssertGetAlertListResponseItemsInnerRequired checks if the required fields are not zero-ed
func AssertGetAlertListResponseItemsInnerRequired(obj GetAlertListResponseItemsInner) error {
	if err := AssertEventRequired(obj.Event); err != nil {
		return err
	}
	return nil
}

// AssertRecurseGetAlertListResponseItemsInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetAlertListResponseItemsInner (e.g. [][]GetAlertListResponseItemsInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetAlertListResponseItemsInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetAlertListResponseItemsInner, ok := obj.(GetAlertListResponseItemsInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetAlertListResponseItemsInnerRequired(aGetAlertListResponseItemsInner)
	})
}
