/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type AlertConfig struct {
	Uuid string `json:"uuid,omitempty"`

	MessageExpression string `json:"message_expression,omitempty"`

	MinPriority string `json:"min_priority,omitempty"`

	Duration string `json:"duration,omitempty"`

	MinRate int32 `json:"min_rate,omitempty"`

	Comment string `json:"comment,omitempty"`
}

// AssertAlertConfigRequired checks if the required fields are not zero-ed
func AssertAlertConfigRequired(obj AlertConfig) error {
	return nil
}

// AssertRecurseAlertConfigRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AlertConfig (e.g. [][]AlertConfig), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAlertConfigRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAlertConfig, ok := obj.(AlertConfig)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAlertConfigRequired(aAlertConfig)
	})
}
