/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetAlertListResponse struct {
	Items []GetAlertListResponseItemsInner `json:"items,omitempty"`
}

// AssertGetAlertListResponseRequired checks if the required fields are not zero-ed
func AssertGetAlertListResponseRequired(obj GetAlertListResponse) error {
	for _, el := range obj.Items {
		if err := AssertGetAlertListResponseItemsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetAlertListResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetAlertListResponse (e.g. [][]GetAlertListResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetAlertListResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetAlertListResponse, ok := obj.(GetAlertListResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetAlertListResponseRequired(aGetAlertListResponse)
	})
}
