/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetAlertListResponseItems struct {
	Uuid string `json:"uuid,omitempty"`

	Message string `json:"message,omitempty"`

	Time string `json:"time,omitempty"`

	Event Event `json:"event,omitempty"`
}

// AssertGetAlertListResponseItemsRequired checks if the required fields are not zero-ed
func AssertGetAlertListResponseItemsRequired(obj GetAlertListResponseItems) error {
	if err := AssertEventRequired(obj.Event); err != nil {
		return err
	}
	return nil
}

// AssertRecurseGetAlertListResponseItemsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetAlertListResponseItems (e.g. [][]GetAlertListResponseItems), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetAlertListResponseItemsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetAlertListResponseItems, ok := obj.(GetAlertListResponseItems)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetAlertListResponseItemsRequired(aGetAlertListResponseItems)
	})
}
