/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetAlertConfigListResponse struct {
	Items []AlertConfig `json:"items,omitempty"`
}

// AssertGetAlertConfigListResponseRequired checks if the required fields are not zero-ed
func AssertGetAlertConfigListResponseRequired(obj GetAlertConfigListResponse) error {
	for _, el := range obj.Items {
		if err := AssertAlertConfigRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetAlertConfigListResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetAlertConfigListResponse (e.g. [][]GetAlertConfigListResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetAlertConfigListResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetAlertConfigListResponse, ok := obj.(GetAlertConfigListResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetAlertConfigListResponseRequired(aGetAlertConfigListResponse)
	})
}
