/*
 * API
 *
 * API for traces
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Filters struct {
	Limit int `json:"limit,omitempty"`

	Component string `json:"component,omitempty"`
}

// AssertFiltersRequired checks if the required fields are not zero-ed
func AssertFiltersRequired(obj Filters) error {
	return nil
}

// AssertRecurseFiltersRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Filters (e.g. [][]Filters), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFiltersRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFilters, ok := obj.(Filters)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFiltersRequired(aFilters)
	})
}
